table Clientes
	lineageTag: 0c21148a-6e0c-4884-90c2-3aacf3b6d838

	column 'ID Cliente'
		dataType: string
		lineageTag: 821fe48a-29fc-4b95-ac45-1a1985f0d462
		summarizeBy: none
		sourceColumn: ID Cliente

		annotation SummarizationSetBy = Automatic

	column 'Nome Cliente'
		dataType: string
		lineageTag: c7cf3c6f-1ef5-4957-af19-039515533c50
		summarizeBy: none
		sourceColumn: Nome Cliente

		annotation SummarizationSetBy = Automatic

	column Segmento
		dataType: string
		lineageTag: 6f5b32fa-20d6-47a0-9546-c36f9c4a74f2
		summarizeBy: none
		sourceColumn: Segmento

		annotation SummarizationSetBy = Automatic

	column Cidade
		dataType: string
		lineageTag: f48357f4-ab0a-4e3f-9267-3c5eed73260f
		summarizeBy: none
		sourceColumn: Cidade

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: 008b74fe-dac0-4701-b9f8-be33d43680f2
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column Pais
		dataType: string
		lineageTag: 1ad13186-aada-40d4-85f3-6274c75cb444
		summarizeBy: none
		sourceColumn: Pais

		annotation SummarizationSetBy = Automatic

	column Mercado
		dataType: string
		lineageTag: 4b314a6c-01f9-43df-9767-5412d23f6df0
		summarizeBy: none
		sourceColumn: Mercado

		annotation SummarizationSetBy = Automatic

	column Regiao
		dataType: string
		lineageTag: 43a5e614-868c-46dc-9bd4-abe23b8253aa
		summarizeBy: none
		sourceColumn: Regiao

		annotation SummarizationSetBy = Automatic

	partition Clientes = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\ALEXANDRE\OneDrive\Área de Trabalho\Exercícios Analista de BI\Clientes.csv"),[Delimiter=";", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}}),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Tipo Alterado", [PromoteAllScalars=true]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"ID Cliente", type text}, {"Nome Cliente", type text}, {"Segmento", type text}, {"Cidade", type text}, {"Estado", type text}, {"Pais", type text}, {"Mercado", type text}, {"Regiao", type text}}),
				    #"Linhas em Branco Removidas" = Table.SelectRows(#"Tipo Alterado1", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null})))
				in
				    #"Linhas em Branco Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

